apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  aws-access: QUtJQTQzQkpPWFNHNEYzWjJTRzM=
  aws-secret: L1gzQWZvdHFadDNaWWN1QTJ3VDBRN0Jrai9sNEYrejFHT3lYT3lILw==
  aws-region: dXMtZWFzdC0y