apiVersion: apps/v1

kind: Deployment

metadata:

  name: backend-deployment

  labels:

    app: backend-deployment

spec:

  replicas: 1

  selector:

    matchLabels:

      app: backend-deployment

  template:

    metadata:

      labels:

        app: backend-deployment

    spec:

      containers:
      - name: mytube-backend-app
        image: keoffor/mytube-backend:v1
        ports:
        - name: backend-port
          containerPort: 8080

        env:
          - name: AWS_ACCESS_KEY_ID 
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: aws-access
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: aws-secret
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: aws-region            
      nodeSelector:
        zone: us-east-1a 


